
package Social;

import javax.swing.*;
import java.sql.*;
import java.util.*;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;


public class starter1 extends javax.swing.JFrame { //sqllite connection 

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement stmt = null;
    String r;
    ArrayList<String> a = new ArrayList<String>();
   
    
   
    public starter1() {
        initComponents();
        UpdateList();
    }
    
    private void UpdateList(){
      conn = sqliteConnection.dbConnector();
      try{
          String sql = "Select * from Account ";
          pst = conn.prepareStatement(sql);
          rs = pst.executeQuery();
          
          
      }catch (SQLException e){
          JOptionPane.showMessageDialog(null,e);
      }
    
        
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        user = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        DeleteFriend = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        homeSearch = new javax.swing.JButton();
        Playlist = new javax.swing.JButton();
        friendsSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        InviteFriend = new javax.swing.JButton();
        search2 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            /*String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            */ArrayList<String> b = new ArrayList<>();
            public int getSize() { return a.size(); }
            public String getElementAt(int i) { return a.get(i); }

        });
        jScrollPane1.setViewportView(jList1);

        DeleteFriend.setText("Delete Friend");
        DeleteFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFriendActionPerformed(evt);
            }
        });

        label2.setBackground(new java.awt.Color(219, 126, 126));
        label2.setForeground(new java.awt.Color(25, 13, 13));
        label2.setPreferredSize(new java.awt.Dimension(70, 29));
        label2.setText("Friends");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addComponent(DeleteFriend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteFriend))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        label1.setBackground(new java.awt.Color(227, 142, 142));
        label1.setText("Plookify");

        homeSearch.setText("Home");
        homeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSearchActionPerformed(evt);
            }
        });

        Playlist.setText("Playlist");

        friendsSearch.setText("Acount");

        jButton1.setText("Radio");

        jButton2.setText("TrackPLayer");

        jButton3.setText("Social");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(148, 50, 23));
        jLabel1.setForeground(new java.awt.Color(18, 8, 8));
        jLabel1.setText("Search");

        search1.setText("Search Friend");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        InviteFriend.setText("Invite Friend");
        InviteFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InviteFriendActionPerformed(evt);
            }
        });
        InviteFriend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InviteFriendKeyPressed(evt);
            }
        });

        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(friendsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InviteFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(669, 749, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(search1))
                            .addComponent(jLabel1)))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InviteFriend, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(search2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(friendsSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeSearchActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
       /*
        try{
            String sql ="select * from Account where Firstname";
            pst=conn.prepareStatament(sql);
            pst.setString(1.showFriend.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
            String add1=rs.getString()
            }
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        */
    }//GEN-LAST:event_searchBarKeyReleased

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        



    }//GEN-LAST:event_searchBarActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
       
 conn = sqliteConnection.dbConnector(); //search function 
   
        try {
            String sql = "select * from Account where Firstname='" + searchBar.getText() + "'";
            if (searchBar.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Not discoravable ");
                 
            } 
        
           
            else {

                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();

                while (rs.next()) {

                    search2.setText(rs.getString("Firstname"));
                    return;
                }
             //   JOptionPane.showMessageDialog(null, "Not subscribed ");
            }
         // if(!rs.next())
         // {
                           JOptionPane.showMessageDialog(null, "Not subscribed ");

         // }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cant find the customer");

        }

    }//GEN-LAST:event_search1ActionPerformed

    private void InviteFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InviteFriendActionPerformed
      
        
        
        String te;
           String name=searchBar.getText();

     //System.out.println(te);
       
       
       if(search2.isShowing()){
        te = JOptionPane.showInputDialog(null,"Accept / Decline"); //friend can either accept or decline the request
            
           if(te.equalsIgnoreCase("Accept")){
                a.add(name);
             //   JList list =new JList(a.toArray());/*
             //   jList1 = list;
             //   System.out.println(a.get(0));*/
                
    DefaultListModel listModel=new DefaultListModel();
    
    for(int i=0; i<a.size(); i++)
    {
      listModel.addElement(a.get(i));
    }
    
     //   System.out.println(listModel);
     jList1.setModel(listModel);
               
              //  jList1=new JList(listModel);
               // jList1.setVisible(true);
                
                //a.add(te);
                //JList list = new JList(a.toArray());
              //  jList1 = list;
            //  jList1.repaint();
           //   jList1.revalidate();

       //         listModel.addElement(te);
          //      jList1=new JList(listModel);
               // JList.setVisible(true);
                
                //a.add(te);
                //JList list = new JList(a.toArray());
              //  jList1 = list;
   //            jList1.validate();
                
                //jList1.setModel(list);
                //jList1.add(search2.getText(), this);
                
              
                        
                        //(search2.getText());
            } 
            
            
            }
        
                
        
        
        
    }//GEN-LAST:event_InviteFriendActionPerformed

    private void InviteFriendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InviteFriendKeyPressed
        
    }//GEN-LAST:event_InviteFriendKeyPressed

    private void DeleteFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFriendActionPerformed
  DefaultListModel model = (DefaultListModel) jList1.getModel();//This method is used to delete selected friends from the friends list
  int selectedIndex = jList1.getSelectedIndex();
   if (selectedIndex != -1) {
    model.remove(selectedIndex);
}        
        
    }//GEN-LAST:event_DeleteFriendActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search2ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(starter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(starter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(starter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(starter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new starter1().setVisible(true);
                
            }
        });
    }
 //These are the buttons that I will be using for my GUI
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteFriend;
    private javax.swing.JButton InviteFriend;
    private javax.swing.JButton Playlist;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton friendsSearch;
    private javax.swing.JButton homeSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton search1;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}